name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Generate build number
        uses: einaregilsson/build-number@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
        env:
          GO111MODULE: 'on'

      - name: Run unit tests
        run: |
          go test -v ./...
        env:
          GO111MODULE: 'on'

      - name: Build
        run: go build -v -o output/k2w
        env:
          GOOS: linux
          GOARCH: amd64
          CGO_ENABLED: 0
          GO111MODULE: 'on'

      - name: Get Docker image tag name
        run: |
          export
          mkdir target
          echo "build-$BUILD_NUMBER" > ./target/TAG_NAME

      - name: Upload binary
        uses: actions/upload-artifact@v1
        with:
          name: k2w
          path: output/k2w

      - name: Upload Dockerfile
        uses: actions/upload-artifact@v1
        with:
          name: docker
          path: Dockerfile

      - name: Build & Push to Docker Hub
        uses: opspresso/action-docker@master
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_NAME: seadiaz/k2w
          LATEST: 'true'
